---
name: Branch
on:
  pull_request:
    branches:
      - itisopen
      - release/**
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    branches:
      - itisopen
      - release/v*
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
      - 'test/**'
      - 'README.md'

permissions: {}

jobs:
  terraform-module:
    uses: itisopen/.github/.github/workflows/shared-terraform-module.yml@itisopen
    secrets: inherit
