---
name: chatops
on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  id-token: write
  contents: write
  statuses: write

jobs:
  test:
    uses: itisopen/.github/.github/workflows/shared-terraform-chatops.yml@itisopen
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/terratest') }}
    secrets: inherit
