---
name: release
on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  terraform-module:
    uses: itisopen/.github/.github/workflows/shared-release-branches.yml@itisopen
    secrets: inherit
