name: auto-release

on:
  push:
    branches:
      - itisopen
      - production

jobs:
  auto:
    uses: itisopen/.github/.github/workflows/shared-auto-release.yml@itisopen
    with:
      publish: true
    secrets: inherit
