name: "Shared terraform module"
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci-terraform:
    uses: itisopen/.github/.github/workflows/shared-ci-terraform.yml@itisopen
    name: "CI"
    with:
      # Workaround for https://github.com/community/community/discussions/9099
      # We should switch to nofilter once it's fixed
      filter-mode: ${{ github.event_name == 'pull_request' && 'diff_context' || 'nofilter' }}
      suggestions: "${{ github.event_name == 'pull_request' }}"
      runs-on: ${{ inputs.runs-on }}

  ci-readme:
    uses: itisopen/.github/.github/workflows/shared-readme.yml@itisopen
    name: "Readme"
    if: ${{ github.event_name == 'push' }}
    with:
      runs-on: ${{ inputs.runs-on }}
    secrets: inherit

  ci-codeowners:
    uses: itisopen/.github/.github/workflows/shared-codeowners.yml@itisopen
    name: "CI"
    with:
      is_fork: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
      runs-on: ${{ inputs.runs-on }}
    secrets: inherit

  ci-labels:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    name: "CI / Labels Validate"
    steps:
      - uses: itisopen/github-action-release-label-validator@v1

  ci:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    if: ${{ always() }}
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
    needs: [ ci-terraform, ci-readme, ci-codeowners, ci-labels ]

  auto-release:
    name: "Release"
    needs: [ci]
    uses: itisopen/.github/.github/workflows/shared-auto-release.yml@itisopen
    if: ${{ github.event_name == 'push' }}
    with:
      runs-on: ${{ inputs.runs-on }}
      publish: true
    secrets: inherit
